name: Packagist Update

on:
  push:
    branches:
      - main

jobs:
  packagist-update:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Packagist
        uses: mnavarrocarter/packagist-update@72b6a490902b9e14e114dd748b112bb49087c642
        with:
          domain: https://packagist.org
          username: const-tech
          api_token: 1777c5533c2f7ff76d6652b7c36d1416e9ddab55
          package_name: almarwa/whatsapp-gateway
